name: AQRUN
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day-:title.html
paginate: 5
paginate_path: '/blog/page:num'
#excerpt_separator: 'excerpt'


plugins: [jekyll-paginate]

#主导航菜单
mainMenus:
  main:
    id: 100
    name: 首页
    href: '/'
  php:
    id: 101
    name: PHP
    href: /blog/php/
  javascript:
    id: 102
    name: Javascript
    href: /blog/javascript/
  java:
    id: 103
    name: Java
    href: /blog/java/
  android:
    id: 104
    name: Android
    href: /blog/android/
  ios:
    id: 105
    name: IOS
    href: /blog/ios/
  ubuntu:
    id: 107
    name: Ubuntu
    href: /blog/ubuntu/
  drupal:
    id: 108
    name: Drupal
    href: /blog/drupal/
  diary:
    id: 106
    name: 随笔
    href: /blog/diary/

customechange: test