name: AQRUN
markdown: kramdown
permalink: /:categories/:year/:month/:day-:title.html
#highlighter: rouge


# Build settings
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md', 'yarn.lock']
#excerpt_separator: 'excerpt'
include: ['assets']

# Site settings 配置站点
title: '子十的独立博客'
description: '热爱技术。很高兴能在这里与你分享我对技术和生活的思考。'
keyword: 'AQRUN,子十,AQRUN的独立博客, 子十的博客, 前端, javascript, vuejs, nodejs, 设计,PHP,java,react,骑行,跑步,爬山'
url: 'http://aqrun.com' # your host

#主导航菜单
mainMenus:
  main:
    id: 100
    name: 首页
    href: '/'
  backend:
    id: 101
    name: 后端开发
    href: /blog/backend/
  frontend:
    id: 102
    name: 前端开发
    href: /blog/frontend/
  server:
    id: 103
    name: 服务器
    href: /blog/server/
  rust:
    id: 108
    name: Rust
    href: /blog/rust/
  diary:
    id: 104
    name: 随笔
    href: /blog/diary/
  #java:
    #id: 103
    #name: Java
    #href: /blog/java/
  #android:
    #id: 104
    #name: Android
    #href: /blog/android/
  #ios:
    #id: 105
    #name: IOS
    #href: /blog/ios/

customechange: test

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Footer
footer:
  since: 2014

# Author 配置博主信息
author: '子十'
nickname: '子十'
bio: '天行健，君子以自强不息。<br/>地势坤，君子以厚德载物。'
avatar: '/assets/img/profile.png?v=0.1'

# Search
search: true

# Night mode
nightMode: true

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/aqrun'
  jianshu: '//www.jianshu.com/u/0b2ee2adc013'
  gitee: '//gitee.com/aqrun'
  github: '//github.com/aqrun'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: 
  - jekyll-paginate-v2

# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  debug: false
  #collection: 'posts'
  per_page: 10
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page:num/' # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2